// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Example;

public interface PrinterPrx extends Ice.ObjectPrx
{
    public void write(String message);

    public void write(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_write(String message);

    public Ice.AsyncResult begin_write(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_write(String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_write(String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_write(String message, Callback_Printer_write __cb);

    public Ice.AsyncResult begin_write(String message, java.util.Map<String, String> __ctx, Callback_Printer_write __cb);

    public Ice.AsyncResult begin_write(String message, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_write(String message, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_write(String message, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_write(String message, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_write(Ice.AsyncResult __result);
}
