// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Example;

public final class PrinterI extends _PrinterDisp
{
    public
    PrinterI()
    {
	
    }

    public void
    write(String message, Ice.Current __current)
    {
    	System.out.println(message);
    }
}
